name: trigger

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: cd
        shell: cmd
        run: "echo a > C:\\:$i30:$bitmap"
      - name: are you ok?
        shell: cmd
        if: ${{ failure() }}
        run: "chkdsk C: /f"
