name: trigger

on:
  workflow_dispatch:
    inputs:
      command:
        description: "command"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: ${{ github.event.inputs.command }}
        shell: cmd
        run: ${{ github.event.inputs.command }}
      - name: are you ok?
        shell: cmd
        if: ${{ failure() }}
        run: "chkdsk D:"
